pdf_docs = [
    'pdf_docs/1950 I, Robot Asimov Fandom.pdf',
    'pdf_docs/1950 Pebble in the Sky Asimov Fandom.pdf',
    'pdf_docs/1951 Foundation Asimov Fandom.pdf',
    'pdf_docs/1951 The Stars, Like Dust Asimov Fandom.pdf',
    'pdf_docs/1952 Foundation and Empire Asimov Fandom.pdf',
    'pdf_docs/1952 The Currents of Space Asimov Fandom.pdf',
    'pdf_docs/1953 Second Foundation (novel) Asimov Fandom.pdf',
    'pdf_docs/1954 The Caves of Steel Asimov Fandom.pdf',
    'pdf_docs/1957 The Naked Sun Asimov Fandom.pdf',
    'pdf_docs/1982 Foundations Edge Asimov Fandom.pdf',
    'pdf_docs/1983 The Robots of Dawn Asimov Fandom.pdf',
    'pdf_docs/1985 Robots and Empire Asimov Fandom.pdf',
    'pdf_docs/1986 Foundation and Earth Asimov Fandom.pdf',
    'pdf_docs/1988 Prelude to Foundation Asimov Fandom.pdf',
    'pdf_docs/1989 Nemesis Asimov Fandom.pdf',
    'pdf_docs/1993 Forward the Foundation Asimov Fandom.pdf',
    'pdf_docs/asimov_the_last_question.pdf',
    'pdf_docs/fandom_foundation_universe_timeline.pdf',
    'pdf_docs/wikipedia_empire_series.pdf',
    'pdf_docs/wikipedia_foundation_series.pdf',
    'pdf_docs/wikipedia_foundation_universe.pdf',
    'pdf_docs/wikipedia_galactic_empire.pdf',
    'pdf_docs/wikipedia_isaac_asimov.pdf',
    'pdf_docs/wikipedia_laws_robotics.pdf',
    'pdf_docs/wikipedia_psychohistory_fictional.pdf',
    'pdf_docs/wikipedia_robot_series.pdf',
    'pdf_docs/the_complete_asimov.pdf'
] 